services:
  phyton.dev:
    build:
      context: .
      dockerfile: Dockerfile
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    volumes:
      - '.:/app'
    networks:
      - practice-1
  mysql:
      image: 'mysql/mysql-server:8.0'
      environment:
          MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
          MYSQL_ROOT_HOST: "%"
          MYSQL_DATABASE: '${DB_DATABASE}'
          MYSQL_USER: '${DB_USERNAME}'
          MYSQL_PASSWORD: '${DB_PASSWORD}'
          MYSQL_ALLOW_EMPTY_PASSWORD: 1
      volumes:
          - 'mysql-data:/var/lib/mysql'
      ports:
          - '${FORWARD_MYSQL_PORT:-3306}:3306'
      networks:
          - practice-1
      healthcheck:
          test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
          retries: 3
          timeout: 5s
  phpmyadmin:
      depends_on:
          - mysql
      image: phpmyadmin/phpmyadmin
      restart: always
      ports:
          - '${FORWARD_PHPMYADMIN_PORT:-8081}:80'
      environment:
          PMA_HOST: mysql
          MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      networks:
          - practice-1
  mongodb:
      image : mongo:latest
      environment:
          - MONGO_INITDB_ROOT_USERNAME=${MONGODB_ROOT_USER}
          - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_ROOT_PASSWORD}
      restart: unless-stopped
      volumes:
          - 'mongodb-data:/data/db'
      ports:
          - '${FORWARD_MONGODB_PORT:-27017}:27017'
      networks:
          - practice-1
  mongo-express:
      image: mongo-express
      environment:
          ME_CONFIG_MONGODB_SERVER: mongodb
          ME_CONFIG_MONGODB_ENABLE_ADMIN: true
          ME_CONFIG_MONGODB_AUTH_DATABASE: admin
          ME_CONFIG_MONGODB_ADMINUSERNAME: "${MONGODB_ROOT_USER}"
          ME_CONFIG_MONGODB_ADMINPASSWORD: "${MONGODB_ROOT_PASSWORD}"
          ME_CONFIG_BASICAUTH_USERNAME: "${MONGO_EXPRESS_ADMIN_USER}"
          ME_CONFIG_BASICAUTH_PASSWORD: "${MONGO_EXPRESS_ADMIN_PASSWORD}"
      depends_on:
          - mongodb
      networks:
          - practice-1
      ports:
          - '${FORWARD_MONGODB_EXPRESS_PORT:-8082}:8082'
      healthcheck:
          test: "wget --quiet --tries=3 --spider http://${MONGO_EXPRESS_ADMIN_USER}:${MONGO_EXPRESS_ADMIN_PASSWORD}@10.10.10.60:8081 || exit 1"
          interval: 30s
          timeout: 10s
          retries: 3
      restart: unless-stopped

networks:
  practice-1:
    driver: bridge

volumes:
    mysql-data:
        driver: local
    mongodb-data:
        driver: local
